name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.27.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_svg: ^2.0.9
  responsive_builder: ^0.7.0
  url_launcher: ^6.2.5
  flutter_inner_shadow: 0.0.1
  logger: ^2.4.0
  equatable: ^2.0.5

  #json_annotation: ^4.9.0
  #formz: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
    - assets/projects/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf

    - family: oceanSans
      fonts:
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-Bold.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-BoldSemiExt.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-BookExt.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-Light.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-Semibold.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-XBold.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-BoldExt.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-Book.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-BookSemiExt.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-LightExt.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-SemiboldExt.ttf
        - asset: assets/fonts/ocean_sans_std/OceanSansStd-XBoldExt.ttf

    - family: cirka
      fonts:
        - asset: assets/fonts/cirka/Cirka-Bold.otf
        - asset: assets/fonts/cirka/Cirka-Light.otf
        - asset: assets/fonts/cirka/Cirka-Variable.ttf
